In [ ]:
library(tidyverse)

In [ ]:
UN_data <- read.csv("final_country_data.csv")

Transforming the data into a wider format

In [ ]:
UN_wide <- UN_data %>%
  pivot_wider(names_from = Variable, values_from = Value)

Selecting a smaller subset of columns.

In [ ]:
UN_wide <- UN_wide %>% select(1:30)
UN_wide

    Country                                   Region
1   Afghanistan                               Southern Asia
2   Albania                                   Southern Europe
3   Algeria                                   Northern Africa
4   American Samoa                            Polynesia
5   Andorra                                   Southern Europe
6   Angola                                    Middle Africa
7   Anguilla                                  Caribbean
8   Antigua and Barbuda                       Caribbean
9   Argentina                                 South America
10  Armenia                                   Western Asia
11  Aruba                                     Caribbean
12  Australia                                 Oceania
13  Austria                                   Western Europe
14  Azerbaijan                                Western Asia
15  Bahamas                                   Caribbean
16  Bahrain                                   Western Asia
17  Bangladesh                                Southern Asia
18  Barbados                                  Caribbean
19  Belarus                                   Eastern Europe
20  Belgium                                   Western Europe
21  Belize                                    Central America
22  Benin                                     Western Africa
23  Bermuda                                   Northern America
24  Bhutan                                    Southern Asia
25  Bolivia (Plurinational State of)          South America
26  Bonaire, Sint Eustatius and Saba          Caribbean
27  Bosnia and Herzegovina                    Southern Europe
28  Botswana                                  Southern Africa
29  Brazil                                    South America
30  British Virgin Islands                    Caribbean
⋮   ⋮                                         ⋮
203 Tajikistan                                Central Asia
204 Thailand                                  South-eastern Asia
205 The former Yugoslav Republic of Macedonia Southern Europe
206 Timor-Leste                               South-eastern Asia
207 Togo                                      Western Africa
208 Tokelau                                   Polynesia
209 Tonga                                     Polynesia
210 Trinidad and Tobago                       Caribbean
211 Tunisia                                   Northern Africa
212 Turkey                                    Western Asia
213 Turkmenistan                              Central Asia
214 Turks and Caicos Islands                  Caribbean
215 Tuvalu                                    Polynesia
216 Uganda                                    Eastern Africa
217 Ukraine                                   Eastern Europe
218 United Arab Emirates                      Western Asia
219 United Kingdom                            Northern Europe
220 United Republic of Tanzania               Eastern Africa
221 United States Virgin Islands              Caribbean
222 United States of America                  Northern America
223 Uruguay                                   South America
224 Uzbekistan                                Central Asia
225 Vanuatu                                   Melanesia
226 Venezuela (Bolivarian Republic of)        South America
227 Viet Nam                                  South-eastern Asia
228 Wallis and Futuna Islands                 Polynesia
229 Western Sahara                            Northern Africa
230 Yemen                                     Western Asia
231 Zambia                                    Eastern Africa
232 Zimbabwe                                  Eastern Africa
    Population (000, 2021) Pop. density (per km2, 2021) Capital city
1   39 835a                61a                          Kabul
2   2 873a                 104.9a                       Tirana
3   44 617a                18.7a                        Algiers
4   55a                    275.5a                       Pago Pago
5   77a                    164.6a                       Andorra la Vella
6   33 934a                27.2a                        Luanda
7   15a                    168.1a                       The Valley
8   99a                    224.4a                       Saint John's
9   45 606a                16.7a                        Buenos Aires
10  2 968a                 104.3a                       Yerevan
11  107a                   595.5a                       Oranjestad
12  25 788a,b              3.4a,b                       Canberra
13  9 043a                 109.7a                       Vienna
14  10 223a,b              123.7a,b                     Baku
15  397a                   39.7a                        Nassau
16  1 748a                 2 300.4a                     Manama
17  166 304a               1 277.6a                     Dhaka
18  288a                   669.1a                       Bridgetown
19  9 443a                 46.5a                        Minsk
20  11 632a                384.2a                       Brussels
21  405a                   17.8a                        Belmopan
22  12 451a                110.4a                       Porto-Novoc
23  62a                    1 241.8a                     Hamilton
24  780a                   20.5a                        Thimphu
25  11 833a                10.9a                        Sucred
26  26a                    80.6a                        Kralendijk
27  3 264a                 64a                          Sarajevo
28  2 397a                 4.2a                         Gaborone
29  213 993a               25.6a                        Brasilia
30  30a                    202.8a                       Road Town
⋮   ⋮                      ⋮                            ⋮
203 9 750a                 69.7a                        Dushanbe
204 69 951a                136.9a                       Bangkok
205 2 083a                 82.6a                        Skopje
206 1 344a                 90.4a                        Dili
207 8 478a                 155.9a                       Lomé
208 1a                     136.8a                       Tokelauc
209 107a                   148.3a                       Nuku'alofa
210 1 403a                 273.6a                       Port of Spain
211 11 936a                76.8a                        Tunis
212 85 043a                110.5a                       Ankara
213 6 118a                 13a                          Ashgabat
214 39a                    41.3a                        Cockburn Town
215 12a                    397.5a                       Funafuti
216 47 124a                235.8a                       Kampala
217 43 467a,b              75a,b                        Kyiv
218 9 991a                 119.5a                       Abu Dhabi
219 68 207a                281.9a                       London
220 61 498a,b              69.4a,b                      Dodoma
221 104a                   297.8a                       Charlotte Amalie
222 332 915a               36.4a                        Washington, D.C.
223 3 485a                 19.9a                        Montevideo
224 33 936a                79.8a                        Tashkent
225 314a                   25.8a                        Port Vila
226 28 705a                32.5a                        Caracas
227 98 169a                316.6a                       Hanoi
228 11a                    79.2a                        Matu-Utu
229 612a                   2.3a                         El Aaiún
230 30 491a                57.8a                        Sana'a
231 18 921a                25.5a                        Lusaka
232 15 092a                39a                          Harare
    Capital city pop. (000, 2021) UN membership date Surface area (km2)
1   4 114.0b                      19-Nov-46          652 864b
2   484.6b                        14-Dec-55          28 748b
3   2 729.3c,b                    08-Oct-62          2 381 741b
4   48.5c                         NA                 199b
5   22.6c                         28-Jul-93          468b
6   8 044.7c,b                    01-Dec-76          1 246 700b
7   1.4d                          NA                 91b
8   20.8d                         11-Nov-81          442b
9   15 057.3d,c                   24-Oct-45          2 796 427b,c
10  1 083.3b                      02-Mar-92          29 743b
11  29.9c                         NA                 180b
12  452.5e,d                      01-Nov-45          7 692 024c,d
13  1 915.3b                      14-Dec-55          83 878b
14  2 313.1d,c                    02-Mar-92          86 600c
15  279.7c                        18-Sep-73          13 940b
16  600.4c,b                      21-Sep-71          778b
17  20 283.6c,b                   17-Sep-74          148 460b
18  89.2c                         09-Dec-66          431b
19  2 016.7c,b                    24-Oct-45          207 600b
20  2 065.3c,b                    27-Dec-45          30 528b
21  23c                           25-Sep-81          22 965b
22  285.3e                        20-Sep-60          114 763b
23  10.1c                         NA                 54b
24  203.3c                        21-Sep-71          38 394b
25  277.9e                        14-Nov-45          1 098 581b,c
26  11.3b,c                       NA                 NA
27  342.7c,b                      22-May-92          51 209b
28  269.3c                        17-Oct-66          582 000b
29  4 559.0c,b                    24-Oct-45          8 515 767b
30  15.1c                         NA                 151b
⋮   ⋮                             ⋮                  ⋮
203 893.8b                        02-Mar-92          142 600b
204 10 350.2b                     16-Dec-46          513 140b
205 589.8b                        08-Apr-93          25 713b
206 281.1c                        27-Sep-02          14 919b
207 1 785.3b                      20-Sep-60          56 785b
208 NA                            NA                 12b
209 22.9c                         14-Sep-99          747b
210 544.3d,b                      18-Sep-62          5 127b
211 2 327.8c,b                    12-Nov-56          163 610b
212 5 018.0c,b                    24-Oct-45          783 562b
213 828.1b                        02-Mar-92          488 100b
214 0.1d                          NA                 948b,c
215 7c                            05-Sep-00          26b
216 3 137.7c,b                    25-Oct-62          241 550b
217 2 973.3c                      24-Oct-45          603 500c
218 1 452.1c                      09-Dec-71          71 024b,c
219 9 176.5d,c                    24-Oct-45          242 495b,c
220 261.6d                        14-Dec-61          947 303c
221 52.3c                         NA                 347b
222 5 264.5b                      24-Oct-45          9 833 517b
223 1 744.7c,b                    18-Dec-45          173 626b
224 2 490.3b                      02-Mar-92          448 969b
225 52.7c                         15-Sep-81          12 189b
226 2 935.5c,b                    15-Nov-45          929 690b
227 4 479.6c,b                    20-Sep-77          331 236b
228 1d                            NA                 142b
229 232.4d                        NA                 266 000b,c
230 2 874.4c,b                    30-Sep-47          527 968b
231 2 646.6b                      01-Dec-64          752 612b
232 1 521.3b                      25-Aug-80          390 757b
    Sex ratio (m per 100 f) National currency          ⋯
1   105.3a                  Afghani (AFN)              ⋯
2   103.6a                  Lek (ALL)                  ⋯
3   102.1a                  Algerian Dinar (DZD)       ⋯
4   NA                      US Dollar (USD)            ⋯
5   NA                      Euro (EUR)                 ⋯
6   97.9a                   Kwanza (AOA)               ⋯
7   NA                      E. Caribbean Dollar (XCD)c ⋯
8   93.4a                   E. Caribbean Dollar (XCD)c ⋯
9   95.3a                   Argentine Peso (ARS)       ⋯
10  88.8a                   Armenian Dram (AMD)        ⋯
11  90.2a                   Aruban Florin (AWG)        ⋯
12  99.2a,b                 Australian Dollar (AUD)    ⋯
13  97.4a                   Euro (EUR)                 ⋯
14  99.9a,b                 Azerbaijan manat (AZN)     ⋯
15  94.6a                   Bahamian Dollar (BSD)      ⋯
16  184.5a                  Bahraini Dinar (BHD)       ⋯
17  102.1a                  Taka (BDT)                 ⋯
18  93.9a                   Barbados Dollar (BBD)      ⋯
19  87.2a                   Belarusian Ruble (BYN)     ⋯
20  98.4a                   Euro (EUR)                 ⋯
21  98.8a                   Belize Dollar (BZD)        ⋯
22  99.8a                   CFA Franc, BCEAO (XOF)d    ⋯
23  NA                      Bermudian Dollar (BMD)     ⋯
24  113.7a                  Ngultrum (BTN)             ⋯
25  100.7a                  Boliviano (BOB)            ⋯
26  NA                      US Dollar (USD)            ⋯
27  95.9a                   Convertible Mark (BAM)     ⋯
28  94.2a                   Pula (BWP)                 ⋯
29  96.5a                   Brazilian Real (BRL)       ⋯
30  NA                      US Dollar (USD)            ⋯
⋮   ⋮                       ⋮                          ⋱
203 101.5a                  Somoni (TJS)               ⋯
204 94.7a                   Baht (THB)                 ⋯
205 100.1a                  Denar (MKD)                ⋯
206 102.1a                  US Dollar (USD)            ⋯
207 99.1a                   CFA Franc, BCEAO (XOF)c    ⋯
208 NA                      New Zealand Dollar (NZD)   ⋯
209 100.2a                  Pa'anga (TOP)              ⋯
210 97.4a                   TT Dollar (TTD)c           ⋯
211 98.4a                   Tunisian Dinar (TND)       ⋯
212 97.5a                   Turkish Lira (TRY)         ⋯
213 97a                     Turkmen. Manat (TMT)c      ⋯
214 NA                      US Dollar (USD)            ⋯
215 NA                      Australian Dollar (AUD)    ⋯
216 97.3a                   Uganda Shilling (UGX)      ⋯
217 86.4a,b                 Hryvnia (UAH)              ⋯
218 222a                    UAE Dirham (AED)d          ⋯
219 97.8a                   Pound Sterling (GBP)       ⋯
220 99.9a,b                 Tanzanian Shilling (TZS)   ⋯
221 90.4a                   US Dollar (USD)            ⋯
222 97.9a                   US Dollar (USD)            ⋯
223 93.6a                   Peso Uruguayo (UYU)        ⋯
224 99.6a                   Uzbekistan Sum (UZS)       ⋯
225 102.7a                  Vatu (VUV)                 ⋯
226 96.7a                   Bolívar (VEF)              ⋯
227 99.7a                   Dong (VND)                 ⋯
228 NA                      CFP Franc (XPF)c           ⋯
229 109.4a                  Moroccan Dirham (MAD)      ⋯
230 101.5a                  Yemeni Rial (YER)          ⋯
231 98.1a                   Zambian Kwacha (ZMW)       ⋯
232 91.4a                   Zimbabwe Dollar (ZWL)      ⋯
    Unemploymenth (% of labour force)
1   11.2c
2   12.8c
3   NA
4   NA
5   NA
6   NA
7   NA
8   NA
9   NA
10  16.6c
11  NA
12  NA
13  4.8c
14  NA
15  NA
16  NA
17  NA
18  NA
19  NA
20  NA
21  NA
22  NA
23  NA
24  NA
25  NA
26  NA
27  NA
28  NA
29  NA
30  NA
⋮   ⋮
203 NA
204 NA
205 16.4c
206 4.6i
207 NA
208 NA
209 NA
210 NA
211 NA
212 NA
213 NA
214 NA
215 NA
216 NA
217 NA
218 NA
219 NA
220 NA
221 NA
222 3.9i
223 NA
224 NA
225 NA
226 NA
227 NA
228 NA
229 NA
230 NA
231 11.4c
232 NA
    Labour force participation rateh (female/male pop. %)
1   21.8 /       74.6c
2   46.6 /       64.4c
3   NA
4   NA
5   NA
6   NA
7   NA
8   NA
9   NA
10  47.0 /       65.8c
11  NA
12  NA
13  55.0 /       66.4c
14  NA
15  NA
16  NA
17  NA
18  NA
19  NA
20  NA
21  NA
22  NA
23  NA
24  NA
25  NA
26  NA
27  NA
28  NA
29  NA
30  NA
⋮   ⋮
203 NA
204 NA
205 43.0 /       67.2c
206 61.9 /       72.7i
207 NA
208 NA
209 NA
210 NA
211 NA
212 NA
213 NA
214 NA
215 NA
216 NA
217 NA
218 NA
219 NA
220 NA
221 NA
222 55.9 /       67.9i
223 NA
224 NA
225 NA
226 NA
227 NA
228 NA
229 NA
230 NA
231 70.4 /       79.0c
232 NA
    CPI: Consumer Price Index (2010=100)
1   150b
2   NA
3   NA
4   NA
5   NA
6   NA
7   107b
8   115b
9   331g,e
10  NA
11  NA
12  NA
13  120c
14  161e
15  NA
16  NA
17  NA
18  NA
19  536d
20  118d
21  NA
22  NA
23  ...
24  106f,d
25  NA
26  NA
27  104d
28  NA
29  NA
30  NA
⋮   ⋮
203 NA
204 NA
205 115c
206 NA
207 115d
208 NA
209 NA
210 NA
211 168d
212 263d
213 NA
214 NA
215 ...
216 111k,d
217 290e
218 112e
219 NA
220 NA
221 NA
222 NA
223 NA
224 173j,k,d
225 117j,k,b
226 NA
227 169d
228 NA
229 NA
230 NA
231 246c
232 117e
    Agricultural production index (2014-2016=100)
1   111b
2   103b
3   112b
4   NA
5   NA
6   110b
7   NA
8   93b
9   113c
10  81b
11  NA
12  89d
13  100b
14  126c
15  101b
16  129b
17  109b
18  106b
19  101b
20  102b
21  99b
22  119b
23  NA
24  99b
25  110c
26  NA
27  105b
28  98b
29  110b
30  NA
⋮   ⋮
203 159b
204 101b
205 96b
206 99b
207 110b
208 106b
209 91b
210 104b
211 106b
212 111b
213 95b
214 NA
215 103b
216 100b
217 109c
218 112c
219 104c
220 107c
221 NA
222 100b
223 102b
224 102b
225 100b
226 91b
227 105b
228 NA
229 NA
230 98b
231 110b
232 113b
    International trade: exports (million current US$)
1   1 022h,c
2   NA
3   28 986e,d
4   NA
5   165j,d
6   72 235e,d
7   NA
8   22h,e
9   54 884e
10  2 520c
11  66d
12  NA
13  164 332h,c
14  13 741e
15  410i,d
16  14 066f,d
17  30 768e,d
18  345d
19  29 040i,d
20  298 313d
21  212d
22  763k,f
23  19d
24  584e,d
25  7 033f
26  NA
27  6 149d
28  4 256d
29  NA
30  NA
⋮   ⋮
203 NA
204 219 084e,c
205 6 633c
206 NA
207 992g,d
208 NA
209 14i,d
210 14 561j,e
211 13 854f,d
212 169 658d
213 NA
214 NA
215 NA
216 4 149d
217 NA
218 376 382f,e
219 399 622e
220 2 793g,e
221 NA
222 1 430 254i
223 6 853d
224 13 281d
225 47i,d
226 2 164e,f
227 282 817g,d
228 NA
229 NA
230 ~0e,d
231 7 805c
232 4 395c
    International trade: imports (million current US$)
1   9 683h,c
2   NA
3   41 678e,d
4   NA
5   1 499j,d
6   40 991e,d
7   NA
8   401h,e
9   42 356e
10  4 541c
11  939d
12  NA
13  162 981h,c
14  10 730e
15  2 790i,d
16  14 193f,d
17  45 777e,d
18  1 501d
19  32 592i,d
20  301 292d
21  787d
22  2 551k,f
23  904d
24  922e,d
25  7 115f
26  NA
27  9 867d
28  6 503d
29  NA
30  NA
⋮   ⋮
203 NA
204 188 668e,c
205 8 709c
206 NA
207 2 488g,d
208 NA
209 350i,d
210 1 076j,e
211 18 392f,d
212 219 514d
213 NA
214 NA
215 NA
216 8 251d
217 NA
218 198 753f,e
219 631 221e
220 10 168g,e
221 NA
222 2 405 382i
223 7 564d
224 20 020d
225 256i,d
226 414e,f
227 262 001g,d
228 NA
229 NA
230 5 298e,d
231 5 314c
232 5 048c
    International trade: balance (million current US$)
1   - 8 661h,c
2   NA
3   - 12 692e,d
4   NA
5   - 1 334j,d
6   31 244e,d
7   NA
8   -380h,e
9   12 528e
10  - 2 021c
11  -873d
12  NA
13  1 351h,c
14  3 011e
15  - 2 380i,d
16  -127f,d
17  - 15 009e,d
18  - 1 156d
19  - 3 553i,d
20  - 2 979d
21  -575d
22  - 1 788k,f
23  -885d
24  -337e,d
25  -82f
26  NA
27  - 3 719d
28  - 2 247d
29  NA
30  NA
⋮   ⋮
203 NA
204 30 416e,c
205 - 2 076c
206 NA
207 - 1 496g,d
208 NA
209 -336i,d
210 13 485j,e
211 - 4 538f,d
212 - 49 856d
213 NA
214 NA
215 NA
216 - 4 102d
217 NA
218 177 628f,e
219 - 231 600e
220 - 7 375g,e
221 NA
222 - 975 128i
223 -711d
224 - 6 740d
225 -209i,d
226 1 750e,f
227 20 816g,d
228 NA
229 NA
230 - 5 298e,d
231 2 491c
232 -653c
    Balance of payments, current account (million US$)
1   - 3 137c
2   - 1 318c
3   - 17 148b
4   NA
5   568b
6   894d
7   -136d
8   -113d
9   2 985e
10  -394c
11  -324d
12  33 829f
13  10 781c
14  -228e
15  - 2 065d
16  - 2 435h
17  1 082d
18  -453n
19  -241d
20  -933d
21  -128d
22  -581b
23  828b
24  -381d
25  -176f
26  NA
27  -635d
28  - 1 397b
29  - 24 074d
30  NA
⋮   ⋮
203 336c
204 16 298c
205 -424c
206 -357i
207 -55b
208 NA
209 -19d
210 1 056b
211 - 3 284b
212 - 37 315d
213 NA
214 173j
215 -9b
216 - 2 333b
217 5 207e
218 NA
219 - 95 421e
220 - 1 301c
221 NA
222 - 647 218i
223 -297d
224 - 3 138d
225 113b
226 - 3 870i

Cleaning the records - alphabet and spaces are removed.

The string '...' represents missing values in the UN dataset. These values were replaced with NA.

In [ ]:
UN_wide_clean <- UN_wide %>%
  mutate(across(c(3:4, 6, 8:9, 11:30),
                ~ na_if(str_replace_all(., "[[:alpha:], ]", ""), "...")))
UN_wide_clean

    Country                                   Region
1   Afghanistan                               Southern Asia
2   Albania                                   Southern Europe
3   Algeria                                   Northern Africa
4   American Samoa                            Polynesia
5   Andorra                                   Southern Europe
6   Angola                                    Middle Africa
7   Anguilla                                  Caribbean
8   Antigua and Barbuda                       Caribbean
9   Argentina                                 South America
10  Armenia                                   Western Asia
11  Aruba                                     Caribbean
12  Australia                                 Oceania
13  Austria                                   Western Europe
14  Azerbaijan                                Western Asia
15  Bahamas                                   Caribbean
16  Bahrain                                   Western Asia
17  Bangladesh                                Southern Asia
18  Barbados                                  Caribbean
19  Belarus                                   Eastern Europe
20  Belgium                                   Western Europe
21  Belize                                    Central America
22  Benin                                     Western Africa
23  Bermuda                                   Northern America
24  Bhutan                                    Southern Asia
25  Bolivia (Plurinational State of)          South America
26  Bonaire, Sint Eustatius and Saba          Caribbean
27  Bosnia and Herzegovina                    Southern Europe
28  Botswana                                  Southern Africa
29  Brazil                                    South America
30  British Virgin Islands                    Caribbean
⋮   ⋮                                         ⋮
203 Tajikistan                                Central Asia
204 Thailand                                  South-eastern Asia
205 The former Yugoslav Republic of Macedonia Southern Europe
206 Timor-Leste                               South-eastern Asia
207 Togo                                      Western Africa
208 Tokelau                                   Polynesia
209 Tonga                                     Polynesia
210 Trinidad and Tobago                       Caribbean
211 Tunisia                                   Northern Africa
212 Turkey                                    Western Asia
213 Turkmenistan                              Central Asia
214 Turks and Caicos Islands                  Caribbean
215 Tuvalu                                    Polynesia
216 Uganda                                    Eastern Africa
217 Ukraine                                   Eastern Europe
218 United Arab Emirates                      Western Asia
219 United Kingdom                            Northern Europe
220 United Republic of Tanzania               Eastern Africa
221 United States Virgin Islands              Caribbean
222 United States of America                  Northern America
223 Uruguay                                   South America
224 Uzbekistan                                Central Asia
225 Vanuatu                                   Melanesia
226 Venezuela (Bolivarian Republic of)        South America
227 Viet Nam                                  South-eastern Asia
228 Wallis and Futuna Islands                 Polynesia
229 Western Sahara                            Northern Africa
230 Yemen                                     Western Asia
231 Zambia                                    Eastern Africa
232 Zimbabwe                                  Eastern Africa
    Population (000, 2021) Pop. density (per km2, 2021) Capital city
1   39835                  61                           Kabul
2   2873                   104.9                        Tirana
3   44617                  18.7                         Algiers
4   55                     275.5                        Pago Pago
5   77                     164.6                        Andorra la Vella
6   33934                  27.2                         Luanda
7   15                     168.1                        The Valley
8   99                     224.4                        Saint John's
9   45606                  16.7                         Buenos Aires
10  2968                   104.3                        Yerevan
11  107                    595.5                        Oranjestad
12  25788                  3.4                          Canberra
13  9043                   109.7                        Vienna
14  10223                  123.7                        Baku
15  397                    39.7                         Nassau
16  1748                   2300.4                       Manama
17  166304                 1277.6                       Dhaka
18  288                    669.1                        Bridgetown
19  9443                   46.5                         Minsk
20  11632                  384.2                        Brussels
21  405                    17.8                         Belmopan
22  12451                  110.4                        Porto-Novoc
23  62                     1241.8                       Hamilton
24  780                    20.5                         Thimphu
25  11833                  10.9                         Sucred
26  26                     80.6                         Kralendijk
27  3264                   64                           Sarajevo
28  2397                   4.2                          Gaborone
29  213993                 25.6                         Brasilia
30  30                     202.8                        Road Town
⋮   ⋮                      ⋮                            ⋮
203 9750                   69.7                         Dushanbe
204 69951                  136.9                        Bangkok
205 2083                   82.6                         Skopje
206 1344                   90.4                         Dili
207 8478                   155.9                        Lomé
208 1                      136.8                        Tokelauc
209 107                    148.3                        Nuku'alofa
210 1403                   273.6                        Port of Spain
211 11936                  76.8                         Tunis
212 85043                  110.5                        Ankara
213 6118                   13                           Ashgabat
214 39                     41.3                         Cockburn Town
215 12                     397.5                        Funafuti
216 47124                  235.8                        Kampala
217 43467                  75                           Kyiv
218 9991                   119.5                        Abu Dhabi
219 68207                  281.9                        London
220 61498                  69.4                         Dodoma
221 104                    297.8                        Charlotte Amalie
222 332915                 36.4                         Washington, D.C.
223 3485                   19.9                         Montevideo
224 33936                  79.8                         Tashkent
225 314                    25.8                         Port Vila
226 28705                  32.5                         Caracas
227 98169                  316.6                        Hanoi
228 11                     79.2                         Matu-Utu
229 612                    2.3                          El Aaiún
230 30491                  57.8                         Sana'a
231 18921                  25.5                         Lusaka
232 15092                  39                           Harare
    Capital city pop. (000, 2021) UN membership date Surface area (km2)
1   4114.0                        19-Nov-46          652864
2   484.6                         14-Dec-55          28748
3   2729.3                        08-Oct-62          2381741
4   48.5                          NA                 199
5   22.6                          28-Jul-93          468
6   8044.7                        01-Dec-76          1246700
7   1.4                           NA                 91
8   20.8                          11-Nov-81          442
9   15057.3                       24-Oct-45          2796427
10  1083.3                        02-Mar-92          29743
11  29.9                          NA                 180
12  452.5                         01-Nov-45          7692024
13  1915.3                        14-Dec-55          83878
14  2313.1                        02-Mar-92          86600
15  279.7                         18-Sep-73          13940
16  600.4                         21-Sep-71          778
17  20283.6                       17-Sep-74          148460
18  89.2                          09-Dec-66          431
19  2016.7                        24-Oct-45          207600
20  2065.3                        27-Dec-45          30528
21  23                            25-Sep-81          22965
22  285.3                         20-Sep-60          114763
23  10.1                          NA                 54
24  203.3                         21-Sep-71          38394
25  277.9                         14-Nov-45          1098581
26  11.3                          NA                 NA
27  342.7                         22-May-92          51209
28  269.3                         17-Oct-66          582000
29  4559.0                        24-Oct-45          8515767
30  15.1                          NA                 151
⋮   ⋮                             ⋮                  ⋮
203 893.8                         02-Mar-92          142600
204 10350.2                       16-Dec-46          513140
205 589.8                         08-Apr-93          25713
206 281.1                         27-Sep-02          14919
207 1785.3                        20-Sep-60          56785
208 NA                            NA                 12
209 22.9                          14-Sep-99          747
210 544.3                         18-Sep-62          5127
211 2327.8                        12-Nov-56          163610
212 5018.0                        24-Oct-45          783562
213 828.1                         02-Mar-92          488100
214 0.1                           NA                 948
215 7                             05-Sep-00          26
216 3137.7                        25-Oct-62          241550
217 2973.3                        24-Oct-45          603500
218 1452.1                        09-Dec-71          71024
219 9176.5                        24-Oct-45          242495
220 261.6                         14-Dec-61          947303
221 52.3                          NA                 347
222 5264.5                        24-Oct-45          9833517
223 1744.7                        18-Dec-45          173626
224 2490.3                        02-Mar-92          448969
225 52.7                          15-Sep-81          12189
226 2935.5                        15-Nov-45          929690
227 4479.6                        20-Sep-77          331236
228 1                             NA                 142
229 232.4                         NA                 266000
230 2874.4                        30-Sep-47          527968
231 2646.6                        01-Dec-64          752612
232 1521.3                        25-Aug-80          390757
    Sex ratio (m per 100 f) National currency          ⋯
1   105.3                   Afghani (AFN)              ⋯
2   103.6                   Lek (ALL)                  ⋯
3   102.1                   Algerian Dinar (DZD)       ⋯
4   NA                      US Dollar (USD)            ⋯
5   NA                      Euro (EUR)                 ⋯
6   97.9                    Kwanza (AOA)               ⋯
7   NA                      E. Caribbean Dollar (XCD)c ⋯
8   93.4                    E. Caribbean Dollar (XCD)c ⋯
9   95.3                    Argentine Peso (ARS)       ⋯
10  88.8                    Armenian Dram (AMD)        ⋯
11  90.2                    Aruban Florin (AWG)        ⋯
12  99.2                    Australian Dollar (AUD)    ⋯
13  97.4                    Euro (EUR)                 ⋯
14  99.9                    Azerbaijan manat (AZN)     ⋯
15  94.6                    Bahamian Dollar (BSD)      ⋯
16  184.5                   Bahraini Dinar (BHD)       ⋯
17  102.1                   Taka (BDT)                 ⋯
18  93.9                    Barbados Dollar (BBD)      ⋯
19  87.2                    Belarusian Ruble (BYN)     ⋯
20  98.4                    Euro (EUR)                 ⋯
21  98.8                    Belize Dollar (BZD)        ⋯
22  99.8                    CFA Franc, BCEAO (XOF)d    ⋯
23  NA                      Bermudian Dollar (BMD)     ⋯
24  113.7                   Ngultrum (BTN)             ⋯
25  100.7                   Boliviano (BOB)            ⋯
26  NA                      US Dollar (USD)            ⋯
27  95.9                    Convertible Mark (BAM)     ⋯
28  94.2                    Pula (BWP)                 ⋯
29  96.5                    Brazilian Real (BRL)       ⋯
30  NA                      US Dollar (USD)            ⋯
⋮   ⋮                       ⋮                          ⋱
203 101.5                   Somoni (TJS)               ⋯
204 94.7                    Baht (THB)                 ⋯
205 100.1                   Denar (MKD)                ⋯
206 102.1                   US Dollar (USD)            ⋯
207 99.1                    CFA Franc, BCEAO (XOF)c    ⋯
208 NA                      New Zealand Dollar (NZD)   ⋯
209 100.2                   Pa'anga (TOP)              ⋯
210 97.4                    TT Dollar (TTD)c           ⋯
211 98.4                    Tunisian Dinar (TND)       ⋯
212 97.5                    Turkish Lira (TRY)         ⋯
213 97                      Turkmen. Manat (TMT)c      ⋯
214 NA                      US Dollar (USD)            ⋯
215 NA                      Australian Dollar (AUD)    ⋯
216 97.3                    Uganda Shilling (UGX)      ⋯
217 86.4                    Hryvnia (UAH)              ⋯
218 222                     UAE Dirham (AED)d          ⋯
219 97.8                    Pound Sterling (GBP)       ⋯
220 99.9                    Tanzanian Shilling (TZS)   ⋯
221 90.4                    US Dollar (USD)            ⋯
222 97.9                    US Dollar (USD)            ⋯
223 93.6                    Peso Uruguayo (UYU)        ⋯
224 99.6                    Uzbekistan Sum (UZS)       ⋯
225 102.7                   Vatu (VUV)                 ⋯
226 96.7                    Bolívar (VEF)              ⋯
227 99.7                    Dong (VND)                 ⋯
228 NA                      CFP Franc (XPF)c           ⋯
229 109.4                   Moroccan Dirham (MAD)      ⋯
230 101.5                   Yemeni Rial (YER)          ⋯
231 98.1                    Zambian Kwacha (ZMW)       ⋯
232 91.4                    Zimbabwe Dollar (ZWL)      ⋯
    Unemploymenth (% of labour force)
1   11.2
2   12.8
3   NA
4   NA
5   NA
6   NA
7   NA
8   NA
9   NA
10  16.6
11  NA
12  NA
13  4.8
14  NA
15  NA
16  NA
17  NA
18  NA
19  NA
20  NA
21  NA
22  NA
23  NA
24  NA
25  NA
26  NA
27  NA
28  NA
29  NA
30  NA
⋮   ⋮
203 NA
204 NA
205 16.4
206 4.6
207 NA
208 NA
209 NA
210 NA
211 NA
212 NA
213 NA
214 NA
215 NA
216 NA
217 NA
218 NA
219 NA
220 NA
221 NA
222 3.9
223 NA
224 NA
225 NA
226 NA
227 NA
228 NA
229 NA
230 NA
231 11.4
232 NA
    Labour force participation rateh (female/male pop. %)
1   21.8/74.6
2   46.6/64.4
3   NA
4   NA
5   NA
6   NA
7   NA
8   NA
9   NA
10  47.0/65.8
11  NA
12  NA
13  55.0/66.4
14  NA
15  NA
16  NA
17  NA
18  NA
19  NA
20  NA
21  NA
22  NA
23  NA
24  NA
25  NA
26  NA
27  NA
28  NA
29  NA
30  NA
⋮   ⋮
203 NA
204 NA
205 43.0/67.2
206 61.9/72.7
207 NA
208 NA
209 NA
210 NA
211 NA
212 NA
213 NA
214 NA
215 NA
216 NA
217 NA
218 NA
219 NA
220 NA
221 NA
222 55.9/67.9
223 NA
224 NA
225 NA
226 NA
227 NA
228 NA
229 NA
230 NA
231 70.4/79.0
232 NA
    CPI: Consumer Price Index (2010=100)
1   150
2   NA
3   NA
4   NA
5   NA
6   NA
7   107
8   115
9   331
10  NA
11  NA
12  NA
13  120
14  161
15  NA
16  NA
17  NA
18  NA
19  536
20  118
21  NA
22  NA
23  NA
24  106
25  NA
26  NA
27  104
28  NA
29  NA
30  NA
⋮   ⋮
203 NA
204 NA
205 115
206 NA
207 115
208 NA
209 NA
210 NA
211 168
212 263
213 NA
214 NA
215 NA
216 111
217 290
218 112
219 NA
220 NA
221 NA
222 NA
223 NA
224 173
225 117
226 NA
227 169
228 NA
229 NA
230 NA
231 246
232 117
    Agricultural production index (2014-2016=100)
1   111
2   103
3   112
4   NA
5   NA
6   110
7   NA
8   93
9   113
10  81
11  NA
12  89
13  100
14  126
15  101
16  129
17  109
18  106
19  101
20  102
21  99
22  119
23  NA
24  99
25  110
26  NA
27  105
28  98
29  110
30  NA
⋮   ⋮
203 159
204 101
205 96
206 99
207 110
208 106
209 91
210 104
211 106
212 111
213 95
214 NA
215 103
216 100
217 109
218 112
219 104
220 107
221 NA
222 100
223 102
224 102
225 100
226 91
227 105
228 NA
229 NA
230 98
231 110
232 113
    International trade: exports (million current US$)
1   1022
2   NA
3   28986
4   NA
5   165
6   72235
7   NA
8   22
9   54884
10  2520
11  66
12  NA
13  164332
14  13741
15  410
16  14066
17  30768
18  345
19  29040
20  298313
21  212
22  763
23  19
24  584
25  7033
26  NA
27  6149
28  4256
29  NA
30  NA
⋮   ⋮
203 NA
204 219084
205 6633
206 NA
207 992
208 NA
209 14
210 14561
211 13854
212 169658
213 NA
214 NA
215 NA
216 4149
217 NA
218 376382
219 399622
220 2793
221 NA
222 1430254
223 6853
224 13281
225 47
226 2164
227 282817
228 NA
229 NA
230 ~0
231 7805
232 4395
    International trade: imports (million current US$)
1   9683
2   NA
3   41678
4   NA
5   1499
6   40991
7   NA
8   401
9   42356
10  4541
11  939
12  NA
13  162981
14  10730
15  2790
16  14193
17  45777
18  1501
19  32592
20  301292
21  787
22  2551
23  904
24  922
25  7115
26  NA
27  9867
28  6503
29  NA
30  NA
⋮   ⋮
203 NA
204 188668
205 8709
206 NA
207 2488
208 NA
209 350
210 1076
211 18392
212 219514
213 NA
214 NA
215 NA
216 8251
217 NA
218 198753
219 631221
220 10168
221 NA
222 2405382
223 7564
224 20020
225 256
226 414
227 262001
228 NA
229 NA
230 5298
231 5314
232 5048
    International trade: balance (million current US$)
1   -8661
2   NA
3   -12692
4   NA
5   -1334
6   31244
7   NA
8   -380
9   12528
10  -2021
11  -873
12  NA
13  1351
14  3011
15  -2380
16  -127
17  -15009
18  -1156
19  -3553
20  -2979
21  -575
22  -1788
23  -885
24  -337
25  -82
26  NA
27  -3719
28  -2247
29  NA
30  NA
⋮   ⋮
203 NA
204 30416
205 -2076
206 NA
207 -1496
208 NA
209 -336
210 13485
211 -4538
212 -49856
213 NA
214 NA
215 NA
216 -4102
217 NA
218 177628
219 -231600
220 -7375
221 NA
222 -975128
223 -711
224 -6740
225 -209
226 1750
227 20816
228 NA
229 NA
230 -5298
231 2491
232 -653
    Balance of payments, current account (million US$)
1   -3137
2   -1318
3   -17148
4   NA
5   568
6   894
7   -136
8   -113
9   2985
10  -394
11  -324
12  33829
13  10781
14  -228
15  -2065
16  -2435
17  1082
18  -453
19  -241
20  -933
21  -128
22  -581
23  828
24  -381
25  -176
26  NA
27  -635
28  -1397
29  -24074
30  NA
⋮   ⋮
203 336
204 16298
205 -424
206 -357
207 -55
208 NA
209 -19
210 1056
211 -3284
212 -37315
213 NA
214 173
215 -9
216 -2333
217 5207
218 NA
219 -95421
220 -1301
221 NA
222 -647218
223 -297
224 -3138
225 113
226 -3870
227 13101
228 NA
229 NA
230 -2419
231 2254
232 -308
    Population growth ratei (average annual %)
1   2.5
2   NA
3   NA
4   NA
5   NA
6   NA
7   NA
8   0.9
9   NA
10  NA
11  NA
12  NA
13  0.7
14  NA
15  NA
16  NA
17  NA
18  NA
19  NA
20  NA
21  NA
22  NA
23  NA
24  NA
25  1.4
26  NA
27  NA
28  NA
29  NA
30  NA
⋮   ⋮
203 NA
204 NA
205 ~0.0
206 NA
207 NA
208 NA
209 NA
210 NA
211 NA
212 NA
213 NA
214 NA
215 1.2
216 NA
217 NA
218 1.3
219 NA
220 NA
221 NA
222 NA
223 NA
224 NA
225 NA
226 NA
227 NA
228 NA
229 NA
230 NA
231 NA
232 NA
    Urban population (% of total population)
1   25.8
2   61.2
3   73.2
4   87.1
5   88
6   66.2
7   100
8   24.5
9   92
10  63.2
11  43.5
12  NA
13  58.5
14  NA
15  83.1
16  89.4
17  37.4
18  31.2
19  79
20  98
21  45.9
22  47.9
23  100

Below cells can be used to randomly sample one record from each dataframe to check the cleanliness of data.

In [ ]:
random_index <- sample(1:nrow(UN_wide), 1)
UN_wide[random_index, ]

  Country                   Region    Population (000, 2021)
1 Wallis and Futuna Islands Polynesia 11a
  Pop. density (per km2, 2021) Capital city Capital city pop. (000, 2021)
1 79.2a                        Matu-Utu     1d
  UN membership date Surface area (km2) Sex ratio (m per 100 f)
1 NA                 142b               NA
  National currency ⋯ Unemploymenth (% of labour force)
1 CFP Franc (XPF)c  ⋯ NA
  Labour force participation rateh (female/male pop. %)
1 NA
  CPI: Consumer Price Index (2010=100)
1 NA
  Agricultural production index (2014-2016=100)
1 NA
  International trade: exports (million current US$)
1 NA
  International trade: imports (million current US$)
1 NA
  International trade: balance (million current US$)
1 NA
  Balance of payments, current account (million US$)
1 NA
  Population growth ratei (average annual %)
1 NA
  Urban population (% of total population)
1 0b

In [ ]:
UN_wide_clean[random_index, ]

  Country                   Region    Population (000, 2021)
1 Wallis and Futuna Islands Polynesia 11
  Pop. density (per km2, 2021) Capital city Capital city pop. (000, 2021)
1 79.2                         Matu-Utu     1
  UN membership date Surface area (km2) Sex ratio (m per 100 f)
1 NA                 142                NA
  National currency ⋯ Unemploymenth (% of labour force)
1 CFP Franc (XPF)c  ⋯ NA
  Labour force participation rateh (female/male pop. %)
1 NA
  CPI: Consumer Price Index (2010=100)
1 NA
  Agricultural production index (2014-2016=100)
1 NA
  International trade: exports (million current US$)
1 NA
  International trade: imports (million current US$)
1 NA
  International trade: balance (million current US$)
1 NA
  Balance of payments, current account (million US$)
1 NA
  Population growth ratei (average annual %)
1 NA
  Urban population (% of total population)
1 0

Removing variables with more than 50% missingness and saving the data as a csv

In [ ]:
UN_wide_clean <- UN_wide_clean %>%
  select_if(~ mean(is.na(.)) <= 0.50)

write_csv(UN_wide_clean, "UN_countries_clean.csv")